#!/bin/bash

echo "Cross-Chain Ping-Pong Demo Setup"
echo "===================================="
echo ""

echo "Prerequisites Check:"
echo "EVM Contract: 0x55D59591773CBdC4a3dc5e38E8Ef1cE85C7Ff365 (Sepolia)"
echo "Solana Program: Cw5hAtJEQp3vEnR4Vejbb8P7VSa5TWFzTrzpMNNEe8TF (Devnet)"
echo ""

echo "Instructions for Cross-Chain Testing:"
echo "========================================="
echo ""
echo "1. TERMINAL 1 - Start EVM Relayer:"
echo "   cd evm"
echo "   npm run relayer"
echo ""
echo "2. TERMINAL 2 - Start Solana Relayer:"
echo "   cd svm/pingpong"
echo "   anchor run relayer"
echo ""
echo "3. TERMINAL 3 - Initialize the Game:"
echo "   cd evm"
echo "   # Initialize game from EVM side"
echo "   npx hardhat run scripts/serve.ts --network sepolia"

echo "📊 Monitoring:"
echo "=============="
echo "• EVM Explorer: https://sepolia.etherscan.io/address/0x55D59591773CBdC4a3dc5e38E8Ef1cE85C7Ff365"
echo "• Solana Explorer: https://explorer.solana.com/address/Cw5hAtJEQp3vEnR4Vejbb8P7VSa5TWFzTrzpMNNEe8TF?cluster=devnet"
echo "• LayerZero Scan: https://testnet.layerzeroscan.com/"
echo ""

echo "🎮 Game Rules:"
echo "=============="
echo "• Ball starts at value: 100,000,000,000,000,000,000 (1e20)"
echo "• Each hit decrements value by 1"
echo "• Maximum 100 rallies"
echo "• Game ends when ball value reaches 0 or max rallies hit"
echo ""

echo "Ready to start cross-chain ping-pong! 🏓"